---
name: Mail-Log-Parse
version: 1.0.2
author:
  - 'Daniel Staal - <DStaal@usa.net>'
abstract: Parse and return info in maillogs.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Basename: 0
  File::Temp: 0.17
  IO::File: 0
  Mail::Log::Exceptions: 0
  Scalar::Util: 0
  Time::Local: 0
  perl: 5.6.1
build_requires:
  Module::Build: 0
  Test::Exception: 0
  Test::Warn: 0
recommends:
  IO::Uncompress::AnyUncompress: 0
provides:
  Mail::Log::Parse:
    file: lib/Mail/Log/Parse.pm
    version: 1.0.2
  Mail::Log::Parse::Postfix:
    file: lib/Mail/Log/Parse/Postfix.pm
    version: 1.0
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
